// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atxejcaplvqgmggmwdsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eGVqY2FwbHZxZ21nZ213ZHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTE0NDMsImV4cCI6MjA2NTgyNzQ0M30.fCkMSXHPI9CWklAwyy-0-RQCOSfSEhEO-lPAHhi2vOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);